// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/host": {
    params: {};
  };
  "/draft/:playerId": {
    params: {
      "playerId": string;
    };
  };
  "/display/:code": {
    params: {
      "code": string;
    };
  };
  "/scores/:code": {
    params: {
      "code": string;
    };
  };
  "/games": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/join" | "/host" | "/draft/:playerId" | "/display/:code" | "/scores/:code" | "/games";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join";
  };
  "routes/host.tsx": {
    id: "routes/host";
    page: "/host";
  };
  "routes/draft.tsx": {
    id: "routes/draft";
    page: "/draft/:playerId";
  };
  "routes/display.tsx": {
    id: "routes/display";
    page: "/display/:code";
  };
  "routes/scores.tsx": {
    id: "routes/scores";
    page: "/scores/:code";
  };
  "routes/games.tsx": {
    id: "routes/games";
    page: "/games";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/join": typeof import("./app/routes/join.tsx");
  "routes/host": typeof import("./app/routes/host.tsx");
  "routes/draft": typeof import("./app/routes/draft.tsx");
  "routes/display": typeof import("./app/routes/display.tsx");
  "routes/scores": typeof import("./app/routes/scores.tsx");
  "routes/games": typeof import("./app/routes/games.tsx");
};