// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/display": {
    params: {};
  };
  "/draft": {
    params: {};
  };
  "/scores": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/display" | "/draft" | "/scores";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/display.tsx": {
    id: "routes/display";
    page: "/display";
  };
  "routes/draft.tsx": {
    id: "routes/draft";
    page: "/draft";
  };
  "routes/scores.tsx": {
    id: "routes/scores";
    page: "/scores";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/display": typeof import("./app/routes/display.tsx");
  "routes/draft": typeof import("./app/routes/draft.tsx");
  "routes/scores": typeof import("./app/routes/scores.tsx");
};