// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/join/:urlCode?": {
    params: {
      "urlCode"?: string;
    };
  };
  "/manage": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/start": {
    params: {};
  };
  "/display": {
    params: {};
  };
  "/display/draft": {
    params: {};
  };
  "/display/tournament": {
    params: {};
  };
  "/draft": {
    params: {};
  };
  "/scores": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/join/:urlCode?" | "/manage" | "/history" | "/start" | "/display" | "/display/draft" | "/display/tournament" | "/draft" | "/scores";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join/:urlCode?";
  };
  "routes/home.manage.tsx": {
    id: "routes/home.manage";
    page: "/manage";
  };
  "routes/home.history.tsx": {
    id: "routes/home.history";
    page: "/history";
  };
  "routes/home.start.tsx": {
    id: "routes/home.start";
    page: "/start";
  };
  "routes/display.tsx": {
    id: "routes/display";
    page: "/display";
  };
  "routes/display.draft.tsx": {
    id: "routes/display.draft";
    page: "/display/draft";
  };
  "routes/display.tournament.tsx": {
    id: "routes/display.tournament";
    page: "/display/tournament";
  };
  "routes/draft.tsx": {
    id: "routes/draft";
    page: "/draft";
  };
  "routes/scores.tsx": {
    id: "routes/scores";
    page: "/scores";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/join": typeof import("./app/routes/join.tsx");
  "routes/home.manage": typeof import("./app/routes/home.manage.tsx");
  "routes/home.history": typeof import("./app/routes/home.history.tsx");
  "routes/home.start": typeof import("./app/routes/home.start.tsx");
  "routes/display": typeof import("./app/routes/display.tsx");
  "routes/display.draft": typeof import("./app/routes/display.draft.tsx");
  "routes/display.tournament": typeof import("./app/routes/display.tournament.tsx");
  "routes/draft": typeof import("./app/routes/draft.tsx");
  "routes/scores": typeof import("./app/routes/scores.tsx");
};